# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/DockerVM/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
      
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  nats:
    image: nats
    restart: always
    ports:
      - 4222:4222